### ISSUE TITLE
phpmyadmin issues

### ISSUE THREAD

**Issue by sumoldeananas** [DevTiagoCruz/NONIOBlocker#1]
![semAddon](https://user-images.githubusercontent.com/48912930/54918233-9aa57700-4ef5-11e9-8cf2-524a584685a9.jpg)
![comAddon](https://user-images.githubusercontent.com/48912930/54918235-9aa57700-4ef5-11e9-929f-1d5e11dc163f.jpg)

No Chrome, interfere com o phpmyadmin em localhost, esconde o texto debaixo do menu superior. Fora isso addon impecavel. Obrigado.

**Comment by DevTiagoCruz** [comment]
A partir da versão 1.15 vai ficar corrigida é so aguardar pelo update. 
Obrigado pelo contributo.

**Comment by DevTiagoCruz** [comment]
A partir da versão 1.15 vai ficar corrigida é so aguardar pelo update.
Obrigado pelo contributo.
