### ISSUE TITLE
Voltou a aprarecer o Nomio no dn.pt

### ISSUE THREAD

**Issue by JoJo512** [DevTiagoCruz/NONIOBlocker#10]
Voltou a aprarecer o Nomio no dn.pt

Por exemplo aqui:
[https://www.dn.pt/edicao-do-dia/09-abr-2020/exames-do-9-ano-suspensos-e-secundario-nas-salas-em-maio-os-cenarios-possiveis-para-as-escolas-12046187.html](url)

Obrigado

**Comment by dippas** [comment]
experimenta usar esta [alternativa](https://github.com/dippas/DeleteNonio)

**Comment by DevTiagoCruz** [comment]
Encontra-se corrigido na v1.40
