### ISSUE TITLE
falta suporte para os jornais desportivos

### ISSUE THREAD

**Issue by j0hnsa** [DevTiagoCruz/NONIOBlocker#2]
Boas,

Seria muito interessante se pudesses bloquear o nonio tambem nos sites desportivos.

Cumprimentos

**Comment by DevTiagoCruz** [comment]
Vou colocar mais alguns, se quiser disponiblizar uma lista dos de seu interesse eu irei juntar mais esses.
Obrigado pelo contributo.

**Comment by DevTiagoCruz** [comment]
A partir da versão 1.17 ou superior já disponivel na store do Chrome e Firefox o número de sites com o bloqueio do NONIO aumentaram. Neste momento existem mais alguns sites de desporto exemplo: "ojogo.pt", "record.pt"
