### ISSUE TITLE
nem sempre bloqueia

### ISSUE THREAD

**Issue by hsl1** [DevTiagoCruz/NONIOBlocker#3]
Reparo que nem sempre bloqueia, em especial em mono de navegação anonimo por vezes falha como demonstra as imagens em baixo.
Tenho activo o plugin para uso em modo anónimo.

actualmente tenho o chrome 74

https://prnt.sc/nig5a0

http://prntscr.com/nig9j2

**Comment by DevTiagoCruz** [comment]
Vou analizar a situação e tentar melhor o plugin.
Obrigado pelo contributo.

**Comment by hsl1** [comment]
Pois por vezes acontece mas nem sempre ele bloqueia.
E reparo que quando bloqueia ele ainda mostra no chrome e depois desaparece assim em 2 segundos? Nao consegues evitar isso?
Até poderia por um counter no icone , mas eu vejo que ele renderiza isso por vezes 
https://drive.google.com/open?id=1T36HOeXgrlP8z-hnQ1QZIJ6rUQAcLJ53

**Comment by hsl1** [comment]
Aqui ja vais na 1.16 mas na store ainda está 1.14

**Comment by DevTiagoCruz** [comment]
O plugin faz o seguinte: 
-Aguarda que a página diga "OK estou carregada" vai analisar se encontra a div do NONIO se encontar destrói. 
Por isso é que acontece aparecer o NONIO e desaparecer, essa foi a solução que arranjei para o código não estar a ser executado e gastar recursos ao utilizador. 
Pode acontecer volta e meia o plugin não conseguir fechar o NONIO por ainda não estar carregado. Vou ver o que consigo melhorar.
Uma solução será fazer o refresh da página.
A versão 1.16 está neste momento em aceitação pela store do Chrome no Firefox já está disponível.

**Comment by DevTiagoCruz** [comment]
Já está disponivel a versão 1.20 nas Stores do Chrome e Firefox com uma lista de mais sites e alguns melhoramentos no código na tentativa de correção do seu problema.

**Comment by spore1998** [comment]
jornal de negocios não está em funcionamento

**Comment by vviera** [comment]
Testei no JN sem problemas, no Correio da Manhã não funciona.
![nonio](https://user-images.githubusercontent.com/51706343/59271850-88152100-8c4c-11e9-8666-0bd22a9bb7b7.jpg)

**Comment by poiou** [comment]
este não está a bloquear (sabado.pt)
https://www.sabado.pt/portugal/detalhe/estes-sao-os-diplomados-que-as-empresas-procuram

**Comment by DevTiagoCruz** [comment]
@spore1998 é possivel dar mais detalhes, por vezes é possivel que seja necessário dar um refresh na página.
@vviera o correio da manha mudou o id da div mas já foi feita a correção está disponivel na v1.24
@poiou já testei e parece estar resolvido, como mencionado acima, por vezes é necessário dar um refresh na página.

**Comment by hsl1** [comment]
sabado, dinheiro vivo e falsh nao funciona, obrigado
dei refresh várias vezes

**Comment by DevTiagoCruz** [comment]
@hsl1 precisava de saber qual o broswer e versão da extensão que usa?

**Comment by hsl1** [comment]
@DevTiagoCruz Tenho o chrome 76 mas o plugin já nao está disponivel por aqui https://chrome.google.com/webstore/detail/nonioblocker/mgjhmbdcblaeiplecddckgalpiceoiaj

plugin 1.22

penso que ele actualize sozinho
