### ISSUE TITLE
embeded

### ISSUE THREAD

**Issue by ne0prodigy** [DevTiagoCruz/NONIOBlocker#4]
on blitz.pt it doesnt load embeded codes like videos or photos from 3rd party sites like instagram

using Firefox Quantum 69.0 (32-bit) on a windows 7 machine

**Comment by ne0prodigy** [comment]
with umatrix - http://prntscr.com/p70zxv

with nonioblocker - http://prntscr.com/p7109g

**Comment by DevTiagoCruz** [comment]
Bom dia @pmfnunes 
Está neste momento corrigido o BUG reportado apartir da v1.29
Obrigado pelo contributo.
