### ISSUE TITLE
Story at "publico.pt" doesn't show up

### ISSUE THREAD

**Issue by sidner** [DevTiagoCruz/NONIOBlocker#5]
Seems that the story body at "publico.pt" is getting deleted from DOM when the page finishes loading. If I stop the page from loading, I can actually see the <p> within ".story__body" div with the text. Is it possible to stop whatever script is running from deleting it? Or maybe capture the <p>s and reinject it into the DOM?

Not that familiar with that an extension can do! 

Verified in latest versions of Chrome and Firefox on MacOS

**Comment by DevTiagoCruz** [comment]
Bom dia @pmfnunes
Está neste momento corrigido o BUG reportado apartir da v1.33
Obrigado pelo contributo.
