### ISSUE TITLE
Problema no publico.pt

### ISSUE THREAD

**Issue by sharksector** [DevTiagoCruz/NONIOBlocker#6]
As notícias do **publico.pt** apresentam algumas linhas de código pelo meio, como mostra a imagem abaixo.

![publico](https://user-images.githubusercontent.com/59490132/71754657-00f4f800-2e7f-11ea-91c1-3d2eb2b24f61.JPG)

O botão **_Continuar a Ler_** no final das notícias também nem sempre funciona. Acontece apenas no Firefox e julgo que comecei a ter este problema após o [Público abandonar a plataforma Nónio](https://www.publico.pt/2019/12/03/tecnologia/noticia/publico-sai-plataforma-nonio-1896067). 
Testei em dois computadores (um deles com uma instalação limpa do Firefox) e tive o mesmo resultado.

**Comment by ne0prodigy** [comment]
confirmo... no firefox aparece essa informação no meio das noticias e o botão "continuar a ler" não funciona
no dn.pt por vezes tb não aparece a noticia por inteiro

**Comment by DevTiagoCruz** [comment]
@duartepita
O jornal Público abandonou a plataforma NONIO, ficando assim arrumado o assunto.
https://www.publico.pt/2019/12/03/tecnologia/noticia/publico-sai-plataforma-nonio-1896067
Obrigado pelo contributo.
