### ISSUE TITLE
Site cm-tv.pt apresenta popup do Nonio

### ISSUE THREAD

**Issue by adiasandre96** [DevTiagoCruz/NONIOBlocker#7]
![image](https://user-images.githubusercontent.com/18745609/72669012-9d450000-3a24-11ea-9bf5-3530f8572872.png)

**Comment by dippas** [comment]
com este [plugin](https://github.com/dippas/DeleteNonio) isso não acontece

**Comment by DevTiagoCruz** [comment]
Encontra-se corrigido na v1.41
